module.exports = {
    TIKTOK_URL_WEB: 'https://www.tiktok.com/',
    TIKTOK_URL_WEBCAST: 'https://webcast.tiktok.com/webcast/',
    TIKTOK_HTTP_ORIGIN: 'https://www.tiktok.com',
    DEFAULT_CLIENT_PARAMS: {
        aid: 1988,
        app_language: 'en-US',
        app_name: 'tiktok_web',
        browser_language: 'en',
        browser_name: 'Mozilla',
        browser_online: true,
        browser_platform: 'Win32',
        browser_version: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
        cookie_enabled: true,
        cursor: '',
        device_platform: 'web',
        did_rule: 3,
        fetch_rule: 1,
        identity: 'audience',
        internal_ext: '',
        last_rtt: 0,
        live_id: 12,
        resp_content_type: 'protobuf',
        screen_height: 1152,
        screen_width: 2048,
        tz_name: 'Europe/Berlin',
        version_code: 180800,
    },
    DEFAULT_REQUEST_HEADERS: {
        Connection: 'keep-alive',
        'Cache-Control': 'max-age=0',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
        Accept: 'text/html,application/json,application/protobuf',
        Referer: 'https://www.tiktok.com/',
        Origin: 'https://www.tiktok.com',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate',
    },
};
