allowBuilds:
  bufferutil: true
  core-js: true
  esbuild: true
  fsevents: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - tiktok-live-api-sdk@0.4.0-beta1
  - tiktok-live-proto@0.2.3
  - tiktok-live-proto@0.2.4
