import {
    ControlAction,
    WebcastAccessControlMessage,
    WebcastAccessRecallMessage,
    WebcastBarrageMessage,
    WebcastBoostCardMessage,
    WebcastBottomMessage,
    WebcastCapsuleMessage,
    WebcastCaptionMessage,
    WebcastChatMessage,
    WebcastControlMessage,
    WebcastEmoteChatMessage,
    WebcastEnvelopeMessage,
    WebcastGameRankNotifyMessage,
    WebcastGiftBroadcastMessage,
    WebcastGiftDynamicRestrictionMessage,
    WebcastGiftMessage,
    WebcastGiftPanelUpdateMessage,
    WebcastGiftPromptMessage,
    WebcastGoalUpdateMessage,
    WebcastGuideMessage,
    WebcastHourlyRankRewardMessage,
    WebcastImDeleteMessage,
    WebcastInRoomBannerMessage,
    WebcastLikeMessage,
    WebcastLinkLayerMessage,
    WebcastLinkMessage,
    WebcastLinkMicArmies,
    WebcastLinkMicBattle,
    WebcastLinkMicBattlePunishFinish,
    WebcastLinkMicLayoutStateMessage,
    WebcastLinkmicBattleTaskMessage,
    WebcastLinkMicFanTicketMethod,
    WebcastLinkMicMethod,
    WebcastLinkStateMessage,
    WebcastLiveGameIntroMessage,
    WebcastLiveIntroMessage,
    WebcastMarqueeAnnouncementMessage,
    WebcastMemberMessage,
    WebcastMsgDetectMessage,
    WebcastNoticeMessage,
    WebcastOecLiveShoppingMessage,
    WebcastPartnershipDropsUpdateMessage,
    WebcastPartnershipGameOfflineMessage,
    WebcastPartnershipPunishMessage,
    WebcastPerceptionMessage,
    WebcastPollMessage,
    WebcastQuestionNewMessage,
    WebcastRankTextMessage,
    WebcastRankUpdateMessage,
    WebcastRoomMessage,
    WebcastRoomNotifyMessage,
    WebcastRoomPinMessage,
    WebcastRoomUserSeqMessage,
    WebcastRoomVerifyMessage,
    WebcastSocialMessage,
    WebcastSpeakerMessage,
    WebcastSubNotifyMessage,
    WebcastSubPinEventMessage,
    WebcastSystemMessage,
    WebcastToastMessage,
    WebcastUnauthorizedMemberMessage,
    WebcastViewerPicksUpdateMessage
} from 'tiktok-live-proto/v3';
import { DecodedWebcastPushFrame, RoomGiftInfo, RoomInfo, WebcastEventMessage } from '@/types/client';
import WebcastWebSocketClient from '@/lib/ws/lib/ws-client';
import TypedEventEmitter from 'typed-emitter';

export enum ControlEvent {
    CONNECTED = 'connected',
    DISCONNECTED = 'disconnected',
    ERROR = 'error',
    RAW_DATA = 'rawData',
    DECODED_DATA = 'decodedData',
    WEBSOCKET_CONNECTED = 'websocketConnected',
    WEBSOCKET_DATA = 'websocketData',
    ENTER_ROOM = 'enterRoom',
}

export enum WebcastEvent {
    // Old Events - Added 1.X.X
    CHAT = 'chat',
    MEMBER = 'member',
    GIFT = 'gift',
    ROOM_USER = 'roomUser',
    SOCIAL = 'social',
    LIKE = 'like',
    QUESTION_NEW = 'questionNew',
    LINK_MIC_BATTLE = 'linkMicBattle',
    LINK_MIC_ARMIES = 'linkMicArmies',
    LIVE_INTRO = 'liveIntro',
    EMOTE = 'emote',
    ENVELOPE = 'envelope',
    FOLLOW = 'follow',
    SHARE = 'share',
    STREAM_END = 'streamEnd',
    CONTROL_MESSAGE = 'controlMessage',
    BARRAGE = 'barrage',

    // New Events - Added >=2.0.4
    SYSTEM = 'system',
    HOURLY_RANK = 'hourlyRank',
    GOAL_UPDATE = 'goalUpdate',
    ROOM_MESSAGE = 'roomMessage',
    CAPTION_MESSAGE = 'captionMessage',
    IM_DELETE = 'imDelete',
    IN_ROOM_BANNER = 'inRoomBanner',
    RANK_UPDATE = 'rankUpdate',
    POLL_MESSAGE = 'pollMessage',
    RANK_TEXT = 'rankText',
    LINK_MIC_BATTLE_PUNISH_FINISH = 'linkMicBattlePunishFinish',
    LINK_MIC_BATTLE_TASK = 'linkMicBattleTask',
    LINK_MIC_FAN_TICKET_METHOD = 'linkMicFanTicketMethod',
    LINK_MIC_METHOD = 'linkMicMethod',
    UNAUTHORIZED_MEMBER = 'unauthorizedMember',
    OEC_LIVE_SHOPPING = 'oecLiveShopping',
    MSG_DETECT = 'msgDetect',
    LINK_MESSAGE = 'linkMessage',
    ROOM_VERIFY = 'roomVerify',
    LINK_LAYER = 'linkLayer',
    ROOM_PIN = 'roomPin',

    // Added 2.0.8-beta1
    SUPER_FAN = 'superFan',
    SUPER_FAN_JOIN = 'superFanJoin',
    SUPER_FAN_BOX = 'superFanBox',

    // Added in v3 migration
    ACCESS_CONTROL = 'accessControl',
    ACCESS_RECALL = 'accessRecall',
    BOOST_CARD = 'boostCard',
    BOTTOM_MESSAGE = 'bottomMessage',
    CAPSULE = 'capsule',
    GAME_RANK_NOTIFY = 'gameRankNotify',
    GIFT_BROADCAST = 'giftBroadcast',
    GIFT_DYNAMIC_RESTRICTION = 'giftDynamicRestriction',
    GIFT_PANEL_UPDATE = 'giftPanelUpdate',
    GIFT_PROMPT = 'giftPrompt',
    GUIDE = 'guide',
    LINK_MIC_LAYOUT_STATE = 'linkMicLayoutState',
    LINK_STATE = 'linkState',
    LIVE_GAME_INTRO = 'liveGameIntro',
    MARQUEE_ANNOUNCEMENT = 'marqueeAnnouncement',
    NOTICE = 'notice',
    PARTNERSHIP_DROPS_UPDATE = 'partnershipDropsUpdate',
    PARTNERSHIP_GAME_OFFLINE = 'partnershipGameOffline',
    PARTNERSHIP_PUNISH = 'partnershipPunish',
    PERCEPTION = 'perception',
    ROOM_NOTIFY = 'roomNotify',
    SPEAKER = 'speaker',
    SUB_NOTIFY = 'subNotify',
    SUB_PIN_EVENT = 'subPinEvent',
    TOAST = 'toast',
    VIEWER_PICKS_UPDATE = 'viewerPicksUpdate',
}


export enum ConnectState {
    DISCONNECTED = 'DISCONNECTED',
    CONNECTING = 'CONNECTING',
    CONNECTED = 'CONNECTED'
}

export type EventHandler<T> = (event: T) => void | Promise<void>;

export type ClientEventMap = {

    // Custom Events
    [WebcastEvent.FOLLOW]: EventHandler<WebcastSocialMessage>,
    [WebcastEvent.SUPER_FAN]: EventHandler<WebcastBarrageMessage>,
    [WebcastEvent.SUPER_FAN_JOIN]: EventHandler<WebcastBarrageMessage>,
    [WebcastEvent.SUPER_FAN_BOX]: EventHandler<WebcastEnvelopeMessage>,
    [WebcastEvent.SHARE]: EventHandler<WebcastSocialMessage>,
    [WebcastEvent.STREAM_END]: (event: { action: ControlAction }) => void | Promise<void>,

    // Control Events
    [ControlEvent.CONNECTED]: EventHandler<TikTokLiveConnectionState>,
    [ControlEvent.DISCONNECTED]: EventHandler<{ code: number, reason?: string }>,
    [ControlEvent.ERROR]: EventHandler<any>,
    [ControlEvent.WEBSOCKET_DATA]: EventHandler<Uint8Array>,
    [ControlEvent.RAW_DATA]: (type: string, data: Uint8Array) => void | Promise<void>,
    [ControlEvent.DECODED_DATA]: (type: string, event: any, binary: Uint8Array) => void | Promise<void>,
    [ControlEvent.WEBSOCKET_CONNECTED]: EventHandler<WebcastWebSocketClient>,
    [ControlEvent.ENTER_ROOM]: EventHandler<DecodedWebcastPushFrame>,

    // Old Message Events - Added 1.X.X
    [WebcastEvent.CHAT]: EventHandler<WebcastChatMessage>,
    [WebcastEvent.MEMBER]: EventHandler<WebcastMemberMessage>,
    [WebcastEvent.GIFT]: EventHandler<WebcastGiftMessage>,
    [WebcastEvent.ROOM_USER]: EventHandler<WebcastRoomUserSeqMessage>,
    [WebcastEvent.SOCIAL]: EventHandler<WebcastSocialMessage>,
    [WebcastEvent.LIKE]: EventHandler<WebcastLikeMessage>,
    [WebcastEvent.QUESTION_NEW]: EventHandler<WebcastQuestionNewMessage>,
    [WebcastEvent.LINK_MIC_BATTLE]: EventHandler<WebcastLinkMicBattle>,
    [WebcastEvent.LINK_MIC_ARMIES]: EventHandler<WebcastLinkMicArmies>,
    [WebcastEvent.LIVE_INTRO]: EventHandler<WebcastLiveIntroMessage>,
    [WebcastEvent.EMOTE]: EventHandler<WebcastEmoteChatMessage>,
    [WebcastEvent.ENVELOPE]: EventHandler<WebcastEnvelopeMessage>,
    [WebcastEvent.CONTROL_MESSAGE]: EventHandler<WebcastControlMessage>,
    [WebcastEvent.BARRAGE]: EventHandler<WebcastBarrageMessage>,

    // New Message Events - Added 2.0.4
    [WebcastEvent.SYSTEM]: EventHandler<WebcastSystemMessage>,
    [WebcastEvent.GOAL_UPDATE]: EventHandler<WebcastGoalUpdateMessage>,
    [WebcastEvent.ROOM_MESSAGE]: EventHandler<WebcastRoomMessage>,
    [WebcastEvent.CAPTION_MESSAGE]: EventHandler<WebcastCaptionMessage>,
    [WebcastEvent.IM_DELETE]: EventHandler<WebcastImDeleteMessage>,
    [WebcastEvent.IN_ROOM_BANNER]: EventHandler<WebcastInRoomBannerMessage>,
    [WebcastEvent.RANK_UPDATE]: EventHandler<WebcastRankUpdateMessage>,
    [WebcastEvent.POLL_MESSAGE]: EventHandler<WebcastPollMessage>,
    [WebcastEvent.RANK_TEXT]: EventHandler<WebcastRankTextMessage>,
    [WebcastEvent.LINK_MIC_BATTLE_PUNISH_FINISH]: EventHandler<WebcastLinkMicBattlePunishFinish>,
    [WebcastEvent.LINK_MIC_BATTLE_TASK]: EventHandler<WebcastLinkmicBattleTaskMessage>,
    [WebcastEvent.LINK_MIC_FAN_TICKET_METHOD]: EventHandler<WebcastLinkMicFanTicketMethod>,
    [WebcastEvent.LINK_MIC_METHOD]: EventHandler<WebcastLinkMicMethod>,
    [WebcastEvent.UNAUTHORIZED_MEMBER]: EventHandler<WebcastUnauthorizedMemberMessage>,
    [WebcastEvent.OEC_LIVE_SHOPPING]: EventHandler<WebcastOecLiveShoppingMessage>,
    [WebcastEvent.MSG_DETECT]: EventHandler<WebcastMsgDetectMessage>,
    [WebcastEvent.LINK_MESSAGE]: EventHandler<WebcastLinkMessage>,
    [WebcastEvent.LINK_LAYER]: EventHandler<WebcastLinkLayerMessage>,
    [WebcastEvent.ROOM_PIN]: EventHandler<WebcastRoomPinMessage>,

    // Added in v3 migration
    [WebcastEvent.ACCESS_CONTROL]: EventHandler<WebcastAccessControlMessage>,
    [WebcastEvent.ACCESS_RECALL]: EventHandler<WebcastAccessRecallMessage>,
    [WebcastEvent.BOOST_CARD]: EventHandler<WebcastBoostCardMessage>,
    [WebcastEvent.BOTTOM_MESSAGE]: EventHandler<WebcastBottomMessage>,
    [WebcastEvent.CAPSULE]: EventHandler<WebcastCapsuleMessage>,
    [WebcastEvent.GAME_RANK_NOTIFY]: EventHandler<WebcastGameRankNotifyMessage>,
    [WebcastEvent.GIFT_BROADCAST]: EventHandler<WebcastGiftBroadcastMessage>,
    [WebcastEvent.GIFT_DYNAMIC_RESTRICTION]: EventHandler<WebcastGiftDynamicRestrictionMessage>,
    [WebcastEvent.GIFT_PANEL_UPDATE]: EventHandler<WebcastGiftPanelUpdateMessage>,
    [WebcastEvent.GIFT_PROMPT]: EventHandler<WebcastGiftPromptMessage>,
    [WebcastEvent.GUIDE]: EventHandler<WebcastGuideMessage>,
    [WebcastEvent.HOURLY_RANK]: EventHandler<WebcastHourlyRankRewardMessage>,
    [WebcastEvent.LINK_MIC_LAYOUT_STATE]: EventHandler<WebcastLinkMicLayoutStateMessage>,
    [WebcastEvent.LINK_STATE]: EventHandler<WebcastLinkStateMessage>,
    [WebcastEvent.LIVE_GAME_INTRO]: EventHandler<WebcastLiveGameIntroMessage>,
    [WebcastEvent.MARQUEE_ANNOUNCEMENT]: EventHandler<WebcastMarqueeAnnouncementMessage>,
    [WebcastEvent.NOTICE]: EventHandler<WebcastNoticeMessage>,
    [WebcastEvent.PARTNERSHIP_DROPS_UPDATE]: EventHandler<WebcastPartnershipDropsUpdateMessage>,
    [WebcastEvent.PARTNERSHIP_GAME_OFFLINE]: EventHandler<WebcastPartnershipGameOfflineMessage>,
    [WebcastEvent.PARTNERSHIP_PUNISH]: EventHandler<WebcastPartnershipPunishMessage>,
    [WebcastEvent.PERCEPTION]: EventHandler<WebcastPerceptionMessage>,
    [WebcastEvent.ROOM_NOTIFY]: EventHandler<WebcastRoomNotifyMessage>,
    [WebcastEvent.ROOM_VERIFY]: EventHandler<WebcastRoomVerifyMessage>,
    [WebcastEvent.SPEAKER]: EventHandler<WebcastSpeakerMessage>,
    [WebcastEvent.SUB_NOTIFY]: EventHandler<WebcastSubNotifyMessage>,
    [WebcastEvent.SUB_PIN_EVENT]: EventHandler<WebcastSubPinEventMessage>,
    [WebcastEvent.TOAST]: EventHandler<WebcastToastMessage>,
    [WebcastEvent.VIEWER_PICKS_UPDATE]: EventHandler<WebcastViewerPicksUpdateMessage>,
};

export const WebcastEventMap: Record<BasicWebcastEventMessage, keyof ClientEventMap> = {
    // Old Events - Added 1.X.X
    'WebcastChatMessage': WebcastEvent.CHAT,
    'WebcastMemberMessage': WebcastEvent.MEMBER,
    'WebcastRoomUserSeqMessage': WebcastEvent.ROOM_USER,
    'WebcastSocialMessage': WebcastEvent.SOCIAL,
    'WebcastLikeMessage': WebcastEvent.LIKE,
    'WebcastQuestionNewMessage': WebcastEvent.QUESTION_NEW,
    'WebcastLinkMicBattle': WebcastEvent.LINK_MIC_BATTLE,
    'WebcastLinkMicArmies': WebcastEvent.LINK_MIC_ARMIES,
    'WebcastLiveIntroMessage': WebcastEvent.LIVE_INTRO,
    'WebcastEmoteChatMessage': WebcastEvent.EMOTE,
    'WebcastEnvelopeMessage': WebcastEvent.ENVELOPE,
    'WebcastBarrageMessage': WebcastEvent.BARRAGE,

    // New Events - Added 2.0.4
    'WebcastSystemMessage': WebcastEvent.SYSTEM,
    'WebcastGoalUpdateMessage': WebcastEvent.GOAL_UPDATE,
    'WebcastRoomMessage': WebcastEvent.ROOM_MESSAGE,
    'WebcastCaptionMessage': WebcastEvent.CAPTION_MESSAGE,
    'WebcastControlMessage': WebcastEvent.CONTROL_MESSAGE,
    'WebcastImDeleteMessage': WebcastEvent.IM_DELETE,
    'WebcastInRoomBannerMessage': WebcastEvent.IN_ROOM_BANNER,
    'WebcastRankUpdateMessage': WebcastEvent.RANK_UPDATE,
    'WebcastPollMessage': WebcastEvent.POLL_MESSAGE,
    'WebcastRankTextMessage': WebcastEvent.RANK_TEXT,
    'WebcastLinkMicBattlePunishFinish': WebcastEvent.LINK_MIC_BATTLE_PUNISH_FINISH,
    'WebcastLinkmicBattleTaskMessage': WebcastEvent.LINK_MIC_BATTLE_TASK,
    'WebcastLinkMicFanTicketMethod': WebcastEvent.LINK_MIC_FAN_TICKET_METHOD,
    'WebcastLinkMicMethod': WebcastEvent.LINK_MIC_METHOD,
    'WebcastUnauthorizedMemberMessage': WebcastEvent.UNAUTHORIZED_MEMBER,
    'WebcastOecLiveShoppingMessage': WebcastEvent.OEC_LIVE_SHOPPING,
    'WebcastMsgDetectMessage': WebcastEvent.MSG_DETECT,
    'WebcastLinkMessage': WebcastEvent.LINK_MESSAGE,
    'WebcastLinkLayerMessage': WebcastEvent.LINK_LAYER,
    'WebcastRoomPinMessage': WebcastEvent.ROOM_PIN,

    // Added in v3 migration
    'WebcastAccessControlMessage': WebcastEvent.ACCESS_CONTROL,
    'WebcastAccessRecallMessage': WebcastEvent.ACCESS_RECALL,
    'WebcastBoostCardMessage': WebcastEvent.BOOST_CARD,
    'WebcastBottomMessage': WebcastEvent.BOTTOM_MESSAGE,
    'WebcastCapsuleMessage': WebcastEvent.CAPSULE,
    'WebcastGameRankNotifyMessage': WebcastEvent.GAME_RANK_NOTIFY,
    'WebcastGiftBroadcastMessage': WebcastEvent.GIFT_BROADCAST,
    'WebcastGiftDynamicRestrictionMessage': WebcastEvent.GIFT_DYNAMIC_RESTRICTION,
    'WebcastGiftPanelUpdateMessage': WebcastEvent.GIFT_PANEL_UPDATE,
    'WebcastGiftPromptMessage': WebcastEvent.GIFT_PROMPT,
    'WebcastGuideMessage': WebcastEvent.GUIDE,
    'WebcastHourlyRankRewardMessage': WebcastEvent.HOURLY_RANK,
    'WebcastLinkMicLayoutStateMessage': WebcastEvent.LINK_MIC_LAYOUT_STATE,
    'WebcastLinkStateMessage': WebcastEvent.LINK_STATE,
    'WebcastLiveGameIntroMessage': WebcastEvent.LIVE_GAME_INTRO,
    'WebcastMarqueeAnnouncementMessage': WebcastEvent.MARQUEE_ANNOUNCEMENT,
    'WebcastNoticeMessage': WebcastEvent.NOTICE,
    'WebcastPartnershipDropsUpdateMessage': WebcastEvent.PARTNERSHIP_DROPS_UPDATE,
    'WebcastPartnershipGameOfflineMessage': WebcastEvent.PARTNERSHIP_GAME_OFFLINE,
    'WebcastPartnershipPunishMessage': WebcastEvent.PARTNERSHIP_PUNISH,
    'WebcastPerceptionMessage': WebcastEvent.PERCEPTION,
    'WebcastRoomNotifyMessage': WebcastEvent.ROOM_NOTIFY,
    'WebcastRoomVerifyMessage': WebcastEvent.ROOM_VERIFY,
    'WebcastSpeakerMessage': WebcastEvent.SPEAKER,
    'WebcastSubNotifyMessage': WebcastEvent.SUB_NOTIFY,
    'WebcastSubPinEventMessage': WebcastEvent.SUB_PIN_EVENT,
    'WebcastToastMessage': WebcastEvent.TOAST,
    'WebcastViewerPicksUpdateMessage': WebcastEvent.VIEWER_PICKS_UPDATE,
};


export type BasicWebcastEventMessage = keyof Omit<
    WebcastEventMessage,
    'WebcastGiftMessage'
>;


export type TikTokLiveConnectionState = {
    isConnected: boolean,
    isConnecting: boolean,
    roomId: string,
    roomInfo: RoomInfo | null,
    availableGifts: RoomGiftInfo | null
};

export type WebcastTypedClient = new () => TypedEventEmitter<ClientEventMap>;
